[package]
name        = "timestamp_benchmark"
version     = "2022.3.1"
authors = [
    "Griffin Leclerc <leclercgriffin@gmail.com>"
]

edition = "2018"

[dependencies]

# Used for benchmarking time intervals
time = "0.1"
crossbeam-channel = "0.5.4"
once_cell = "1.10.0"
config      = "0.12.0"